### ISSUE TITLE
Toaster crashes on os x when kemper tuner is activated

### ISSUE THREAD

**Issue by allenhuish** [virango/Toaster#6] opened 2016-02-04 08:54 UTC
I didn't save a crash report.

Tuner activated using footswitch

I am running osx 10.11.3

**Comment by virango** [comment] 2016-04-23 16:03
I think this is a duplicate of #2.

**Comment by virango** [comment] 2016-04-29 21:52
Definitely duplicate of #2. Fixed. Reason was a bad packaging. There was an outdated libtoasterwidgets.dynlib inside of the pkg file (why?).

**Closed as completed by virango** 2016-04-29 21:52 UTC
Labels: duplicate
