### ISSUE TITLE
Toaster shows value of 0.0 on EQ, but LEDS on knobs indicate -5.0

### ISSUE THREAD

**Issue by skoczy** [virango/Toaster#9] opened 2016-05-02 21:05 UTC
Windows 7-32bit, Toaster 1.0.100 ALPHA

Toaster, while started shows 0.0 on EQ knobs but LEDS are far left to -5.0
![image](https://cloud.githubusercontent.com/assets/16901952/14967883/083a9ad4-10ba-11e6-822d-9fac4182d06e.png)

After turning knobs full left by mouse, Toaster now shows -5.0 and it shows 0.0 at noon (top LED)
![image](https://cloud.githubusercontent.com/assets/16901952/14967944/53dc1012-10ba-11e6-8b94-38b97c5b1861.png)

**Comment by skoczy** [comment] 2016-05-02 21:06
Now toaster shows 0.0 when top LED is lit.
![image](https://cloud.githubusercontent.com/assets/16901952/14967977/8284a654-10ba-11e6-806e-9ecbba79fe1f.png)

**Comment by jsharpe** [comment] 2017-01-31 19:33
I have a fix for this issue, I will post a pull request in a few days to fix this.

**Comment by virango** [comment] 2017-01-31 19:52
@jsharpe: You can reproduce this one? Never occured on my systems.
I thought this was a local midi communication problem.

**Comment by jsharpe** [comment] 2017-01-31 22:31
Yes, when my midi device is set to the apple network midi interface and hence its not received any data. The issue is basically a missing redraw request from the initial data.  Issue #14 is very similar, I know why thats occurring but haven't worked out a fix yet. Will probably address both issues at the same time.

**Comment by virango** [comment] 2017-02-01 07:24
I'm not sure if you are aware of the fact that the editor strongly relies on a working 2-way midi communication. After starting, it connects to and requests data from the profiler. Connecting means: open midi in and out ports and send the connection beacon. The beacon is sent periodically every 5 secs and while it is sent the profiler sends some data (e.g. state of the stomp boxes etc.). 
I didn't see the necessity to sync the knob graphic with it's initial value, both are updated after the requested data is received from profiler. But that's not a big issue.
Skoczys problem is another story. What you can deduce from his snapshots is that the communication worked just partly and not all requested parameters were received (the name of the rig, state and type of the stomp were; gain, equalizer values were not).

**Comment by jsharpe** [comment] 2017-02-02 20:40
I agree that #8 looks to be due to flaky midi connections. I think getting the knob to sync visually to the internal state is a good idea for the future as it facilitates moving towards being able to do offline editing.

**Comment by virango** [comment] 2017-02-03 06:24
Agreed.

**Closed as completed** 2017-02-04 17:18 UTC
Labels: help wanted
